# Generated by Django 4.2.3 on 2023-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.CharField(max_length=100)),
                ('IP', models.CharField(max_length=100)),
                ('SN', models.CharField(max_length=100)),
                ('Marque', models.CharField(max_length=100)),
                ('Disk', models.CharField(max_length=100)),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Support', models.CharField(max_length=100)),
            ],
        ),
    ]
