# Generated by Django 4.2.3 on 2023-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='Date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='SN',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
