# Generated by Django 4.2.3 on 2023-08-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_incident_alter_inventaire_date_alter_inventaire_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
