# Generated by Django 4.2.3 on 2023-08-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_inventaire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='SN',
            field=models.CharField(max_length=100),
        ),
    ]
