# Generated by Django 4.2.3 on 2023-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_incident_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='Discription',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='Date',
            field=models.DateField(max_length=100),
        ),
    ]
