# Generated by Django 4.2.3 on 2023-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_rename_discription_incident_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Application',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='incident',
            name='Type',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='Position',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='Site',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='Type',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
