# Generated by Django 4.2.3 on 2023-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_incident_application_incident_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='Position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='Site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='Type',
            field=models.CharField(max_length=1000),
        ),
    ]
