# Generated by Django 4.2.3 on 2023-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_alter_inventaire_position_alter_inventaire_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Application',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Type',
            field=models.CharField(max_length=1000),
        ),
    ]
